version = "1.0"

[main]
name = "django_example_ynh configuration"
services = ["__APP__"]

    [main.config]
    name = "Configuration Options"

        [main.config.debug_enabled]
        ask = "Enable DEBUG mode"
        type = "boolean"
        yes = "1"
        no = "0"
        help = "Should be never enabled in production!"
        bind = "debug_enabled:__FINALPATH__/settings.py"
